<template>
  <div class=" min-h-screen">
    <div class="bg-white w-full masonry-with-columns gap-4 p-4">
      <div v-for="archive in archives" :key="archive" class="border-2 border-black text-black p-2 bg-white">
        <p v-html="archive"></p>
      </div>
    </div>
  </div>
</template>
<script>
    export default {
        components: {

        },
        data() {
            return {
              archives : [
                "Fragments de pensées",
                "éveil source savoir fleur <br> étincelle raison curiosité insectes <br> flamme jour études collecte <br> clarté conscience entomologie schéma <br> lampe doux coton graine <br> savoir phare nature terre",
                "Assembler",
                "De l’ombre à la lumière <br> De l’aube au crépuscule <br> Lumière sombre <br> Sombre lueur",
                'Champs de vision <span class="float-right">perspective</span>',
                "As-tu la volonté de bâtir quelque chose de beau ?",
                "Tu écris ton histoire",
                "Toute parole enferme une vérité. <br> Les cadeaux pourrissent dans le panier. <br>Reste <br>L’encre et le papier. <br>Livres et lettres, univers de papier.<br> Carnets secrets <br>Finiront tous aux archives.",
                "Mémoire écrite.",
                "La chance n’est que l’admiration du hasard.",
                "Sur la plus petite feuille de trèfle, scientillent des gouttes au clair de lune. <br> Ni grand ni petit, ni riche ni pauvre, n’est privé de l’éclat du ciel.",
                "Papillons toxiques <br>Papillon de nuit <br>Nuits blanches, idées noires <br>À m’en détruire le corps, la chair <br>Y a des choses qui me poussent à croire <br>Qu’il n’y a plus rien.",
                "Mes veines pourrissent. <br> J’suis en boucle, j’écris c’que j’pense. <br>Ma tête hurle dans ce silence, d’une nuit estivale <br>Les autres s’amusent pendant que d’autres crèvent <br>Ça a toujours été comme ça.",
                "Il n’y a plus d’espoir pour ce monde.<br>Rendez-moi ma voix ;",
                "Études des sciences naturelles",
                "Théorie des signatures",
                "Poésie de l’observation <br>Collecte d’objets <br>Matérialisme conscient <br>Éveil de la curiosité <br>  Passe-temps, herbe et soleil <br>  Fleurs mortes, os séchés<br>  Gants et ciseaux dans le sac<br>Odeur de résine, insectes<br>  Craqués à l’alcool<br>Peroxyde d’acétone<br>Bois mort, arbres tordus<br>  Les fruits attendent la mort",
                "Dentelle Enluminure Textes Sculpture <br>Codes Cryptage Symbole Histoire<br>Ambiance Script Rouages Collages<br>Couleurs Récits Contes chroniques Requiem",
                "Grand est celui qui n’a pas perdu son coeur d’enfant.",
                "Capreolus Capreolus",
                "Le jardin perdu",
                "Fleur du mal<br>惡の華<br>Aku no hana",
                "Cendres tournoyantes au pied de la colline irréelle.<br>Au-delà des eaux scintillantes<br>Lentement, Délicatement, Silencieusement. Dans le néant.<br>Les lèvres des sages deviennent ébènes, les os gelés tremblent.<br>Avant qu’un oeil ne cligne, au loin dans le ciel,<br>J’observerai votre chute.",
                '<div class="text-center">化け物</div><br>Je suis ce qui est montré du doigt<br>Je suis ce que vous n’êtes pas<br>Je suis votre différence<br>Je suis incompris<br>Monde perforé de sens<br>Jugements constants<br>Regards pesants<br>Sur mes fragiles épaules<br>Mon monde s’écroule',
                "L’esthétique du beau n’existe que dans le monde des idées.",
                "Observer<br>Hyper light Drifter<br>Layer of fear<br>Librairie de Babel<br>IB<br>Witch's Heart<br>Yume Nikki<br>Strawberry Cubes<br>Ruiner<br>Home Sweet Home...",
                "Je souris à mes monstres.",
                "J’ai su, de nouveau que ce soir-là, je n’allais pas rêver.<br>Le monde que j’avais vu en rêve se referme.",
                //
                "<div class='text-center'>(ナナ)</div><br> tu es aussi fière et libre qu’un chat errant blessé dont les plaies ne cicatrisent pas",
                "Idée sans sens.<br>Conception complexe.<br>Yeux de la mort.",
                "Singularité",
                "Odeur de tabac froid sur les draps.<br>Cendres.",
                "L’indifférence est une paralysie de l’âme.",
                "Le corps n’est que l’enveloppe de l’âme.",
                "Comment vivre dans un corps qui veut mourir ?",
                "avidement<br>affamé<br>cupide<br>ardent<br>envieux<br>haletant<br>passionné<br>altéré<br>avare<br>curieux<br>impatient<br>rapace<br>amoureux<br>béant<br>désireux<br>insatiable<br>anxieux<br>dévorant<br>âpre",
                "Kekro - Monde de fou",
                "Béton gris<br>Metro boulot dodo<br>Travail à la chaine<br>On perd notre vie à la gagner<br>Besoin d’arrêter le temps<br>Mais ici pas l’temps de s’arrêter.",
                "J’veux pas d’un futur à vendre, ni d’un passé à racheter.<br>J’veux pas être dans l’sens de la marche, j’suis ni à gauche, ni à droite,<br>j’ai pas de temps à gâcher !",
                "Cette spirale infernale, la pyramide sociale",
                "L’heure tourne",
                "On passe nos vies à courir après le temps, alors que celui-ci n’est qu'une conception imaginaire.",
                "États d’âmes",
                "Tant qu’on est là<br>- TSR",
                "J’suis insolent mais tolérant.",
                "...on se serait shooté à la vitamine C si c’était interdit...",
                "La destruction est une forme de création.",
                "T’aurais le courage de te faire sauter la cervelle ?",
                "Trouver une putain de raison d’vivre.<br>J’ai frappé dans les murs mais ça raisonne vide.<br>Tu me fais du mal quand t’étales ton bien... (Humanoïd.)",
                "Dans l’fond on est tous pareil, sous le ciel ébène on s’croise,<br>on s’pose des questions, sans savoir si c’est les bonnes<br>Profite de la nuit si elle est belle... Quelques angoisses à noyer, le jour se lève, les chiens s’arrêtent d’aboyer.",
                "J’oublierai pas<br>Oubliez-moi<br>- furax",
                "Ville. Concentration d’humains dans un espace réduit.<br>Stress et travail.<br>Routine. Argent.<br>Oppression. Corruption.<br>Règles imposées. Lois imposées.<br>Justice injuste.<br>Rythme configuré.<br>Angoisse constante.<br>Vie de groupe.<br>Troupeaux de morts.<br>Solitude.<br>Devoirs.<br>Chute.",
                "Obscurantisme, conspiration.",
                "Vivre libre ou mourir.",
                "Mort. Peur. Proche. Guerre. Injustice. Sang. Grands et Petits. Écrasés. Frappés. Gazés. Coupés. Militaires. Armes à feu. Fenêtre brisées. Éclats. Sanglots. Infractions. Massacres. Mensonges. Rires. Haine. Monde. Fatalisme. Temps. Dimensions. Réalité. Destinée. Mouvement. Trou noir.",
                "Notre grande guerre est spirituelle. Notre plus grande dépression, c’est nos vies.",
                'Conséquences<span class="float-right">Répercussions</span>',
                "Qui accumule les richesses à beaucoup à perdre.",
                "Ce ne sont pas ceux qui parlent le plus, qui ont des choses à dire.",
                "Mieux vaut allumer une chandelle que de maudire l’obscurité.",
                "Philosophie des Lumières",
                "L’astrolabe.",
                "Lumière<br>Clarté<br>Brilliant<br>Aveuglant<br>Brûler<br>Flamme<br>Lueur<br>Savoir<br>Lampe<br>Phare<br>Rayon<br>Vérité<br>Etincelle<br>Aurore<br>Jour<br>Énigmatique<br>Conscient<br>Doux<br>Innocence",
                "Vertus et vices.",
                "Lucide<br>Perçant<br>Éveillé<br>Aiguisé<br>Perspicace<br>Spirituel<br>Ouvert<br>Esprit<br>Abstrait<br>Symbolique<br>Fictif<br>Imaginaire<br>Collectif<br>Masse<br>Individu<br>Absurde<br>Idéal<br>Faux<br>Utopie<br>Fatalité",
                "Être : fatale abstraction.<br>Regarde autour de toi, comment le monde est beau. Non.<br>Comme ça vit. Comme ça meurt.<br>Être à se quitter. C’est ainsi que nous sommes.<br>Des dieux immobiles nous regardent périr, nous les fixons décédés.<br>C’est ainsi que les hautes ombres nous nomment : êtres.",
                "Oeil<br>Réflexion<br>Vision<br>Perception<br>Regard<br>Observation<br>Conception<br>Rêve<br>Vue<br>Illusion<br>Pupille<br>Iris<br>Rétine<br>Nerf optique<br>Cornée<br>Lumière<br>Flou",
                "Tout est; rien n’est.<br>L’une et l’autre formule aportent une égale sérénité.<br>L’anxieux, pour son malheur, reste entre les deux.<br>Toujours à la merci d’une nuance<br>Incapable de s’établir dans la sécurité de l’être ou de l’absence d'être.<br>(De l'inconvénient d'être né, Cioran.)",
                "Culture de l’immanence.",
                "Le vide, le plein <br>Fallait trouver un entre-deux <br>Entre 2 mondes <br>Bourré de fautes <br>Écrire pour combler <br>Les feuilles se noircissent... <br>Apprendre à être meilleur <br>Tu écris ton histoire <br>Produire pour mourir <br>Mourir en produit <br>Se mentir, mentir aux autres <br>Décider de ne pas choisir <br>Egoïsme ? <br>Lâcheté ? <br>L’altruisme se cultive <br>Creusant l’angoisse <br>Il y a de l’espoir ",
                "Clairvoyance.",
                "Folie pure.",
                "Comment savoir si on a le contrôle ? (Mr Robot)",
                "Si la haine répond à la haine, comment la haine finira-t-elle ?",
                "Vacuité",
                "Calme<br>Confinement<br>Bien-être<br>Mal-être<br>Enfermé<br>Prison<br>Territoire<br>Dispute<br>Colère<br>Excitation<br>Cause<br>Chaine<br>Répercussion",
                "Inévitable<br>Humain<br>Caractère<br>Sentiment<br>Juste<br>Injuste<br>Notion morale<br>Engendrement<br>Entrainement<br>Ressentir<br>Réfléchir<br>Agir<br>Abstinence",
                "Écrire pour combler, écrire sans dire. Tuer le temps.",
                "Ris, et tout le monde rira avec toi.<br>Pleure, et tu seras tout seul à pleurer",
                "L’espace d’une vie est le même, qu’on le passe en chantant ou en pleurant.",
                "Tempête interne<br>Le brouillard se lève<br>Flou<br>Déstabilisant<br>Pensées nébuleuses<br>Des étoiles éclatantes<br>La lumière me tranche les yeux<br>Vision trouble<br>Rêve<br>Réveille-toi<br>Réveille-toi<br>Réveille-toi<br>Le vent arrache les mots<br>La pluie me glace le sang<br>Veines<br>La fenêtre est ouverte<br>Mains froides<br>Mes larmes inondent ma chambre<br>Je hurle au vent<br>La crise passe",
                "Compréhension<br>Fondamental<br>Harmonie<br>Palette<br>Infini<br>Couleurs<br>Conception<br>Mélasse<br>Réalité<br>Absorption<br>Psychique<br>Fiction<br>Esprit<br>Illusion<br>Interprétation<br>A priori",
                "Écoute et apprends.",
                "Onirique<br>Irréel<br>Univers<br>Dimension<br>Perspective<br>Subjectif<br>Question<br>Personne<br>Lieu<br>Etablir<br>Fleur<br>Eclat<br>Ecume<br>Mélancolie<br>Nuage<br>Tempête",
                "Neurasthénie.",
                //liste centrée ? par 3 colonnes aaa
                "<div class='text-center'>pluie</div><br>Chute	Déluge	Averse<br>Bombe	Eau	Feu<br>Brouillard	Saturation	Buée<br>Ombre	Ténèbres	Erreur",
                "Rouge<br>Rubis<br>Écarlate<br>Bordeaux<br>Flamboyant<br>Feu<br>Empourpré<br>Honte<br>Boyaux<br>Vermeil<br>Veine<br>Âme<br>Organe<br>Brulant<br>Muqueuse<br>Hémoglobine<br>Désir<br>Colère",
                "Monstre<br>Abominable<br>Ecoeurant<br>Repoussant<br>Démon<br>Damné<br>Rejet<br>Laideur<br>Dérangeant<br>Malheureux<br>Différent<br>Dangereux<br>Mal<br>Inhumain<br>Mauvais",
                "L’égarement peut mener à la perte de soi-même.<br>Les idées qui pourrissent les pensées maintiennent les doutes.",
                "Théorie des paradoxes.",
                "Les corps et les epsrits s’affaiblissent<br>Les nuages s’étalent à l'infini<br>Et les plaines gelées sont sans fin<br>Ce paysage monotone et glacé semble nous avaler. (Ergo Proxy, ep 7)",
                "... Et ils cherchèrent à résoudre des problèmes plus importants,<br>tels que les phénomènes de la Lune,<br>ceux du Soleil<br>et des Étoiles,<br>enfin, la génèse de l’Univers.",
                "Tous les êtres qui errent dans les ténèbres recherchent la lumière,<br>Mais une fois qu’ils l’atteingnent, ils sont aveuglés<br>Ils détournent le regard et en ressentent une douleur encore plus profonde<br>Il en est de même pour la vérité<br>Le jour viendra où ton regard sera embrasé par la lumière de la vérité.<br>Tu connaitras alors les ténèbres éternels. (Ergo Proxy, ep 9)",
                "Là où est votre trésor, <br>là aussi est votre coeur;<br>Et notre trésor est là où bourdonnent les ruches de nos connaissances.<br>C’est vers ces ruches<br>que nous sommes sans cesse en chemin,<br>En véritable insectes ailés qui butinent le miel de l’esprit.",
                "Théorie du chaos.",
                "Fumeux<br>Nébuleux<br>Flottant<br>Confus<br>Timide<br>Léger<br>Imparfait<br>Vaporeux<br>Nuageux",
                "<div class='text-center'>BETON</span><br>Ciment<br>Obstacle<br>Paralysie<br>Impuissance<br>Force<br>Énergie<br>Activité<br>Effort<br>Animation<br>Éveil<br>Éclat	Étincellant",
                "Cosmos et chaos.<br>Plérôme, monde céleste, plénitude.",
                "Ambivalence ; Caractère de ce qui comporte deux composantes de sens contraire, ou de ce qui se présente sous deux aspects.",
                "Plus les circonstances seront contre toi, plus ta force intérieure sera éclatante.",
                "Demander ne coûte qu’un instant d’embarras, ne pas demander c’est être embarassé toute sa vie.",
                "<div class='text-center'>Piano</div><br>Solitude - Sofiane Pamart<br>Minor Fantasy - Chilly Gonzales<br>Prelude in E-Minor (op.28 no. 4) - Frederic Chopin",
                "À défaut de pouvoir m’exprimer, je me suis créé un ami imaginaire.",
                "Tu es une oeuvre d’art, tu es une muse. Je pourrais te contempler pendant des heures et des heures.",
                "Tout va si vite.",
                "Ils auront beau te dire qu’ils sont là pour t’aider, que tu n’es pas seul. ICi, les murs sont froids, blancs, vides. Un peu comme dans ma tête.",
                "Et tu ne t’es jamais senti aussi épuisé. Alors tu fermes tes yeux rouges et cernés par les larmes, afin d’oublier le froid des matins d’automne.",
                "Lève la tête.",
                "On vit seul, on meurt seul.",
                "Nous voyons tout et pourtant nous ne distinguons rien.",
                "Dans la lumière, les gens ne peuvent que voir. Dans cette situation, tout le monde peut attaquer. Si tu restes dans l’ombre, si tu vis dans la solitude, tu pourras faire ce que tu veux.",
                "J’ai du mal à vivre en ce moment. Je me sens plus trop moi-même.",
                "Reste étrange, les gens chiants s’en iront.",
                "J’ai tout noté dans mon carnet.",
                "C’est terrible vous savez, de se dire que tout ce que l’on créée, peut se détruire. Il n’y a pas de retour en arrière. On est seul face au monde, seul face aux autres, face à tout.",
                "Ne compte que sur toi même ! Retiens bien ça",
                "Mauvaise herbe",
                "Le vilain petit canard",
                "C’est trop d’aimer, tu me fais peur.<br>C'est trop d’aimer quand l’autre en meurt.<br>C’est trop d’aimer quand on en meurt.<br>(J. Bousquet)",
                "Nocturne op.9 No.2",
                "Problème d'émotion - Igorrr",
                "Le silence strident sifflait dans mes oreilles ce soir-là, seule, solitude se prit de moi.",
                "Voilà que l’été s’agonise, <br>Le brouillard prend possession de ton esprit.<br>La capuche te tombe sur le front.",
                "Sang d’encre",
                "Je n’entends pas les discussions autour de moi, à vrai dire, je n’en ai que très peu d'intérêt.",
                "07 Chains of Blame 呵責連鎖",
                "La fleur d’hier est le rêve d’aujourd'hui.",
                "Principe d’équité.",
                "FUTU-RISK",
                "L’être humain est la pire gangrène de ce monde. Il pourrit son extérieur aussi bien que son intérieur. Il manipule et se fait manipuler. Son esprit est aussi minable tant qu’il reste bloqué dans ses idéaux, tant qu’il ne se remet pas en question. Il se pense maître de ses actions mais il ne suit qu’un chemin, celui qui est tracé par les circonstances extérieures, de ce qui l’entoure.",
                "<div class='text-center'>Astrologie chinoise : </div><br>Rat<br>Buffle<br>Tigre<br>Lapin<br>Dragon (2000)<br>Serpent<br>Cheval<br>Chèvre<br>Singe<br>Coq<br>Chien<br>Cochon",
                "野良猫 - chat errant",
                "Ne t’arrête jamais de créer.",
                "L’art c’est aussi exercer des choses nouvelles. D’apprendre. D’aller toujours plus loin.",
                "J’ai pour habitude de prendre beaucoup trop d’affaires avec moi dans mon sac. Et après j’ai mal au dos.",
                "Il n’y a aucune fleur<br>Il ne devrait pas y avoir de fleur.<br>Certains en étaient convaincus<br>Mais ils avaient tort, elle était là.<br>Personne ne l’avait jamais vue.<br>Cela devait être dur à entendre.",
                "Peut-être que j’avais un problème ?",
                "M’angoissant à l’idée que tout peut s’arrêter, je crains les lendemains.<br>Mais je sais que je ne trouverai aucune réponse<br>En regardant les jours défiler.",
                "Puis vient le calme.",
                "Pauvre âme égarée dans les ténèbres. Tu fais le mal et méprise ton prochain. Ton âme est à jamais souillée par le crime. Veux-tu à présent goûter à la mort ?",
                "L’expression de pensées, de soi-même à travers un médium.",
                "Ma feuille était trop petite, j’avais besoin d’espace.",
                "Mots / Maux de têtes.",
                "La nuit je fais des cauchemars.",
                "Je ne porte aucun jugement, j'observe et je relate.",
                "Sois pas un mouton, pense par toi-même !",
                "J’évite le soleil, rester dans l’ombre c’est mon fardeau.",
                "Les médias de l'alienation.",
                "Le monde ne tourne pas autour du soleil, mais de la corruption.",
                "Transition d’une enfance de merde.",
                "L’ouragan cause l'irréparable. la tempête emporte avec elle tous les souvenirs.",
                "Les gouttes de pluie transpercent les vitres, une sirène siffle au loin. Le ciel est blanc, cassant. La lumière est si dense qu’elle me fatigue encore plus que la fumée. Une atmosphère calme, un acouphène assourdissant grise mon ouïe, l’encre se noircit.",
                "La vie est une boucle qui se répète<br>Une spirale infernale infinie<br>Quel est le sens de ce spectacle ?",
                "L’être humain est bruyant.<br>Mais l’être qui vit dans ma tête l’est encore plus.",
                "Toute cette haine... ne fais que nourrir le cycle de haine.",
                "On ne le dit jamais assez souvent<br>Que chaque être est potentiel<br>Et qu’il a le droit de rêver<br>Que la progression de sa vie ne dépend que de lui-même.",
                "Déconstruis tes opinions.",
                "Les stéréotypes ne sont que des idées préconçues.",
                "Si tu fais assez attention, tu percevras la splendeur de la simplicité de la vie.",
                "La vie est étrange.",
                "Offrir",
                "Il y a des gens qui changent. D'autres pas.<br>Mais les jours continuent de passer lentement... Sans qu’on s’en rende compte, le temps s’égrène.",
                "On m’a trop souvent dit que j’avais pas ma place.",
                "La vie est comme une palette infinie de couleurs.",
                "L’auto-suffisance est la clé d'un bonheur certain.",
                "Echo du calme.",
                "Le ciel est un cimetière d'étoiles.",
                "L’éducation me fait douter de mes propres capacités. À croire que mon intellect est défaillant.",
                "La personne qui se respecte et qui respecte les autres, est le plus respectable.",
                "Douce fleur<br>Aux angoisses hivernales.<br>Tu te fânes dans mes mains.<br>C’est la mélancolie de ton sort.<br>De ton âme<br>Émane la couleur<br>De mon sang<br>Émane l’aberrance.",
                "L’humain et la machine.<br>L’humain est la machine.",
                "L’école n'apprend pas à vivre.",
                "Êtres humains, ces systèmes biologiques dotés d’une conscience, d’un sens émotionnel. Leurs cerveaux réduits à des écrans imagés ne se rendent pas compte de la complexité de leur mécanisme. Bien trop souvent manipulés par ces Géants qui tirent les ficelles, la société nous rend aussi dociles et froids qu’une machine métallique inerte.",
                "Mais tout au fond de nous, nous savons, se trouve un coeur.<br>Le processeur actif rouge merveille saignant, sensible au monde extérieur et aussi précieux qu’un rubis.",
                "Arrêt Conscience 66",
                "Soyez conscient de vos actes, de ce que vous dites, de ce que vous faites.",
                "music : 05 Memory (Ib OST)<br>Fullmetal Alchemist Brotherhood OST 3 - Sorrowful Stone<br>Fukasawa Hideyuki (深澤秀行) - Nakamura Sawa no Kyoukan (仲村佐和の叫喚)<br>Jigoku Shoujo - Ost - Kumo To Rouba To Shoujo",



                "De l'ombre à la lumière...",





              ],
            }
        },
        methods: {
        }
    }
</script>
<style lang="scss">
.masonry-with-columns {
columns: 3 200px;
column-gap: 1rem;
div {
  margin: 0 1rem 1rem 0;
  display: inline-block;
  width: 95%;
}
}
</style>
